version: '3'
services:
  app:
    build: .
    ports:
      - "7000:6000"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
volumes:
  mongo-data: