version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
