apiVersion: v1
kind: Service
metadata:
  name: e-commerce
spec:
  type: LoadBalancer
  selector:
    app: mcart
  ports: 
    - protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 30200